server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

spring:
  application:
    name: "auth-service"
  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    routes:
      enabled: true
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE