services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s



  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761
    volumes:
      - /home/mhalim/.m2:/root/.m2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s



  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - 8081:8081
    volumes:
      - /home/mhalim/.m2:/root/.m2
      - ./auth-service:/app
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - RABBITMQ_SERVER=rabbitmq
    depends_on:
      eureka-server:
        condition: service_healthy



  jwt-service:
    build: ./jwt-service
    container_name: jwt-service
    ports:
      - 8083:8083
    volumes:
      - /home/mhalim/.m2:/root/.m2
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - RABBITMQ_SERVER=rabbitmq
    depends_on:
      eureka-server:
        condition: service_healthy



  profile-service:
    build: ./profile-service
    container_name: profile-service
    ports:
      - 8082:8082
    volumes:
      - /home/mhalim/.m2:/root/.m2
      - /home/mhalim/Projects/Twitter/twitter-clone-backend-microservice/db:/app/db
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - RABBITMQ_SERVER=rabbitmq
    depends_on:
      eureka-server:
        condition: service_healthy


  tweet-service:
    build: ./tweet-service
    container_name: tweet-service
    ports:
      - 8084:8084
    volumes:
      - /home/mhalim/.m2:/root/.m2
      - /home/mhalim/Projects/Twitter/twitter-clone-backend-microservice/db:/app/db
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - RABBITMQ_SERVER=rabbitmq
    depends_on:
      eureka-server:
        condition: service_healthy
